name: torrent_tracker
description: Http/Https and UDP torrent tracker/scrape Dart library. It's for implementing bittorrent client.
version: 1.3.12
repository: https://github.com/eclipseglory/torrent_tracker
issue_tracker : https://github.com/eclipseglory/torrent_tracker/issues
publish_to: https://pub.dev/

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  dartorrent_common:
    path: ../dartorrent_common
  bencode_dart:
    path: ../bencode_dart

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  torrent_model:
    path: ../torrent_model
