name: torrent_tracker
description: Http/Https and UDP torrent tracker/scrape Dart library. It's for implementing bittorrent client.
version: 1.3.12
repository: https://github.com/eclipseglory/torrent_tracker
issue_tracker : https://github.com/eclipseglory/torrent_tracker/issues
publish_to: https://pub.dev/

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  dartorrent_common:
    git:
      url: https://github.com/xhns/dartorrent_common.git
  bencode_dart:
    git:
      url: https://github.com/xhns/bencode_dart.git

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  torrent_model:
    git:
      url: https://github.com/xhns/torrent_model.git
